// Startup idea pool for the BUILD2PITCH event (29 Ideas)
// Provided directly from event specifications.

module.exports = [
  {
    title: 'LunchBox',
    shortDescription: 'Pre-order meals from local and home food providers with delivery and subscription options.',
    problemStatement: 'Pre-order meals from local/home food providers.',
    targetAudience: 'Students, office employees, busy individuals',
    category: 'Food & Local Services',
    industry: 'Food & Local Services',
    revenueModel: 'Commission per order, delivery fee, subscription plans',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Meal pre-ordering & scheduled dispatch',
      'Local/home kitchen verified onboarding',
      'Weekly & monthly meal subscription plans',
      'Real-time delivery partner tracking',
    ],
  },
  {
    title: 'CustomTees',
    shortDescription: 'Custom apparel platform for college clubs and events with bulk order pricing.',
    problemStatement: 'Order customized college/event T-shirts.',
    targetAudience: 'Students, college clubs, event participants',
    category: 'E-Commerce & Fashion',
    industry: 'E-Commerce & Fashion',
    revenueModel: 'Profit margin per T-shirt, bulk-order pricing',
    complexityLevel: 'beginner',
    keyFeatures: [
      'Interactive online T-shirt design customizer',
      'Instant bulk discount quotation calculator',
      'College club & fest merch storefront',
      'Digital proof approval & doorstep batch delivery',
    ],
  },
  {
    title: 'BookSwap',
    shortDescription: 'Buy, sell, or exchange used textbooks directly with peers on campus.',
    problemStatement: 'Buy, sell or exchange used textbooks.',
    targetAudience: 'Students',
    category: 'Education & Marketplace',
    industry: 'Education & Marketplace',
    revenueModel: 'Transaction fee, premium membership',
    complexityLevel: 'beginner',
    keyFeatures: [
      'Campus textbook peer-to-peer exchange',
      'Course & syllabus-aligned book directory',
      'Escrow payment & handover verification',
      'Semester-end textbook buyback program',
    ],
  },
  {
    title: 'NotesHub',
    shortDescription: 'Curated marketplace to share, discover, and monetize quality academic study notes.',
    problemStatement: 'Share or sell quality study notes.',
    targetAudience: 'School and college students',
    category: 'Education',
    industry: 'Education',
    revenueModel: 'Paid notes, premium subscription, seller commission',
    complexityLevel: 'beginner',
    keyFeatures: [
      'Verified top-scorer study notes repository',
      'Subject, department, and university filters',
      'Sample page preview with dynamic watermarking',
      'Creator payout wallet and note rating system',
    ],
  },
  {
    title: 'TutorNear',
    shortDescription: 'Connect students with verified local tutors for personalized academic mentoring.',
    problemStatement: 'Connect students with local tutors.',
    targetAudience: 'School and college students',
    category: 'Education',
    industry: 'Education',
    revenueModel: 'Commission per booking, tutor subscription',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Hyperlocal tutor discovery and matching',
      'Subject expertise, rating, and hourly rate filters',
      'Verified tutor background and qualification checks',
      'Automated session booking, calendar sync, and attendance',
    ],
  },
  {
    title: 'ProjectMate',
    shortDescription: 'Collaboration network connecting student builders and project partners.',
    problemStatement: 'Connect students with people needing project help.',
    targetAudience: 'Students working on academic projects',
    category: 'Education & Freelancing',
    industry: 'Education & Freelancing',
    revenueModel: 'Platform commission, premium project listings',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Academic project partner collaboration board',
      'Tech stack and skill complement matching',
      'Milestone-based project task tracking',
      'Verified student project showcase portfolio',
    ],
  },
  {
    title: 'DesignQuick',
    shortDescription: 'Fast on-demand graphic design services for local businesses and event organizers.',
    problemStatement: 'Businesses request posters, logos and designs.',
    targetAudience: 'Small businesses, startups, event organizers',
    category: 'Design & Freelancing',
    industry: 'Design & Freelancing',
    revenueModel: 'Design service fees, monthly business plans',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Streamlined creative design brief wizard',
      'Guaranteed 24-hour turnaround templates',
      'Direct in-app designer chat and revision rounds',
      'Cloud brand asset library and font repository',
    ],
  },
  {
    title: 'EventSnap',
    shortDescription: 'Platform for event photographers to showcase work and deliver high-res photos to attendees.',
    problemStatement: 'Event photographers showcase and deliver photos.',
    targetAudience: 'Event attendees, students, families, event organizers',
    category: 'Events & Photography',
    industry: 'Events & Photography',
    revenueModel: 'Photographer booking commission, premium packages',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Face-recognition photo discovery for attendees',
      'Event photo album hosting with watermark protection',
      'Photographer portfolio discovery and quotation booking',
      'High-resolution digital downloads and print ordering',
    ],
  },
  {
    title: 'FreelanceLocal',
    shortDescription: 'Bridge connecting local neighborhood businesses with skilled student freelancers.',
    problemStatement: 'Local businesses find student freelancers.',
    targetAudience: 'Local business owners',
    category: 'Freelancing & Business',
    industry: 'Freelancing & Business',
    revenueModel: 'Commission per project, freelancer subscription',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Local business task and gig marketplace',
      'Student identity and skill competency badge system',
      'Milestone-based escrow payment release',
      'Direct local business reviews and testimonials',
    ],
  },
  {
    title: 'SlotBook',
    shortDescription: 'Hassle-free appointment booking and queue management for local salons.',
    problemStatement: 'Appointment booking for salons.',
    targetAudience: 'Salon customers',
    category: 'Appointment Services',
    industry: 'Appointment Services',
    revenueModel: 'Booking commission, monthly subscription for salons',
    complexityLevel: 'beginner',
    keyFeatures: [
      'Live salon chair and slot availability calendar',
      'Stylist selection with transparent rate cards',
      'Automated SMS/WhatsApp appointment reminders',
      'Zero-wait digital queue pass',
    ],
  },
  {
    title: 'FixNear',
    shortDescription: 'Reliable on-demand discovery and booking for local electricians, plumbers, and mechanics.',
    problemStatement: 'Find local electricians, plumbers and repair services.',
    targetAudience: 'Homeowners, tenants, households',
    category: 'Local Services',
    industry: 'Local Services',
    revenueModel: 'Commission per service booking, service-provider subscription',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'On-demand nearby technician dispatch',
      'Standardized upfront service rate card',
      'Background-verified and vetted service professionals',
      'Emergency household repair hotline and booking',
    ],
  },
  {
    title: 'LaundryGo',
    shortDescription: 'Doorstep laundry booking service offering scheduled pickup, professional cleaning, and delivery.',
    problemStatement: 'Laundry pickup and delivery booking.',
    targetAudience: 'Students, working professionals, households',
    category: 'Local Services',
    industry: 'Local Services',
    revenueModel: 'Commission per order, pickup and delivery charges',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Scheduled doorstep laundry pickup and drop-off',
      'Wash, fold, steam iron, and dry-cleaning options',
      'Real-time laundry cycle progress tracking',
      'Semester student wash subscriptions',
    ],
  },
  {
    title: 'BakeOrder',
    shortDescription: 'Online marketplace to customize and order artisanal cakes from verified home bakers.',
    problemStatement: 'Order customized cakes and home-baked products.',
    targetAudience: 'Customers planning birthdays, celebrations and events',
    category: 'Food & E-Commerce',
    industry: 'Food & E-Commerce',
    revenueModel: 'Commission per order, delivery fees',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Custom cake 3D visual builder & photo upload',
      'Verified home baker menus & ingredient transparency',
      'Weight, flavor, and eggless dietary customization',
      'Temperature-controlled safe celebration delivery',
    ],
  },
  {
    title: 'GiftNow',
    shortDescription: 'Curated local gifting platform for fast personalized gift crafting and same-day delivery.',
    problemStatement: 'Order personalized gifts locally.',
    targetAudience: 'People buying gifts for birthdays, anniversaries and special occasions',
    category: 'E-Commerce & Gifts',
    industry: 'E-Commerce & Gifts',
    revenueModel: 'Product margin, personalization charges',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Laser-engraved & photo-printed gift customizer',
      'Same-day local gift delivery guarantee',
      'Personalized greeting card audio/text editor',
      'Calendar-based automated occasion reminder alerts',
    ],
  },
  {
    title: 'PartyPlan',
    shortDescription: 'Simplified booking platform for small events, party decoration, catering, and entertainment.',
    problemStatement: 'Book small-event and party services.',
    targetAudience: 'Families, students, individuals planning celebrations',
    category: 'Events & Services',
    industry: 'Events & Services',
    revenueModel: 'Event booking commission, planning service fees',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'All-inclusive celebration package builder',
      'Bundled decor, sound system, DJ, and catering vendors',
      'Smart budget calculator and expense distributor',
      'Live event preparation checklist and vendor coordinator',
    ],
  },
  {
    title: 'WashBook',
    shortDescription: 'Convenient scheduling app for car and bike washing, detailing, and polish services.',
    problemStatement: 'Schedule vehicle washing and detailing.',
    targetAudience: 'Car and bike owners',
    category: 'Automotive Services',
    industry: 'Automotive Services',
    revenueModel: 'Booking commission, car wash business subscriptions',
    complexityLevel: 'beginner',
    keyFeatures: [
      'Doorstep mobile wash or station booking slot',
      'Eco-friendly foam and waterless cleaning options',
      'Vehicle maintenance and polish history tracker',
      'Monthly recurring vehicle wash pass',
    ],
  },
  {
    title: 'PetCare',
    shortDescription: 'All-in-one pet care marketplace connecting owners with groomers, sitters, and clinics.',
    problemStatement: 'Find pet-care and grooming services.',
    targetAudience: 'Pet owners',
    category: 'Pet Services',
    industry: 'Pet Services',
    revenueModel: 'Commission per booking, premium pet-care packages',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Verified neighborhood pet sitters and dog walkers',
      'At-home pet grooming and bath session scheduling',
      'Veterinary consultation booking & vaccination reminder',
      'Emergency pet boarding facility locator',
    ],
  },
  {
    title: 'RentIt',
    shortDescription: 'Hyperlocal rental marketplace to rent electronics, appliances, and gear affordably.',
    problemStatement: 'Rent small items instead of buying them.',
    targetAudience: 'Students, households, individuals',
    category: 'Rental Marketplace',
    industry: 'Rental Marketplace',
    revenueModel: 'Rental commission, security or service fees',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Short-term catalog for electronics, cameras, and projectors',
      'Security deposit escrow protection',
      'Accidental damage warranty coverage',
      'Doorstep item delivery and return inspection logistics',
    ],
  },
  {
    title: 'ToolShare',
    shortDescription: 'Community-powered peer rental platform for power tools, repair kits, and hardware.',
    problemStatement: 'Rent tools and equipment from the community.',
    targetAudience: 'DIY users, households, technicians, hobbyists',
    category: 'Rental & Community',
    industry: 'Rental & Community',
    revenueModel: 'Rental commission, membership plans',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Hyperlocal community tool and hardware sharing library',
      'Power drill, lawnmower, and repair kit listings',
      'Tool condition photos and user safety manuals',
      'Hourly or daily affordable micro-rental rates',
    ],
  },
  {
    title: 'EventMini',
    shortDescription: 'Minimalist event registration and ticketing solution for college clubs and communities.',
    problemStatement: 'Create events and collect registrations.',
    targetAudience: 'Students, clubs, communities, event participants',
    category: 'Events & Registration',
    industry: 'Events & Registration',
    revenueModel: 'Ticketing fees, premium event listings',
    complexityLevel: 'beginner',
    keyFeatures: [
      'One-minute custom event landing page creator',
      'Automated QR code entry pass generation',
      'Real-time attendee check-in and scan app',
      'Instant UPI payment gateway integration',
    ],
  },
  {
    title: 'TrainerBook',
    shortDescription: 'Discover and book certified local fitness trainers, yoga instructors, and dieticians.',
    problemStatement: 'Book local fitness and personal-training sessions.',
    targetAudience: 'Gym users, fitness enthusiasts, beginners',
    category: 'Fitness & Wellness',
    industry: 'Fitness & Wellness',
    revenueModel: 'Booking commission, trainer subscription',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Certified trainer directory with workout specializations',
      'Flexible home, park, or gym training session booking',
      'Tailored fitness goal and nutrition plan builder',
      'Client workout adherence and body metric tracker',
    ],
  },
  {
    title: 'HomeFood',
    shortDescription: 'Hyperlocal platform connecting home chefs with students and working professionals.',
    problemStatement: 'Discover and order homemade food.',
    targetAudience: 'Students, working professionals, families',
    category: 'Food & Local Services',
    industry: 'Food & Local Services',
    revenueModel: 'Commission per order, delivery fee',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Curated daily regional home-cooked meal menus',
      'Monthly tiffin subscription and pause/resume calendar',
      'Kitchen hygiene check and food safety ratings',
      'Direct contact-free home delivery network',
    ],
  },
  {
    title: 'LocalCart',
    shortDescription: 'Empowering neighborhood brick-and-mortar stores with easy online ordering and delivery.',
    problemStatement: 'Online ordering for a neighborhood shop.',
    targetAudience: 'Local residents and neighborhood shoppers',
    category: 'E-Commerce',
    industry: 'E-Commerce',
    revenueModel: 'Seller commission, delivery fee, featured listings',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Instant digital catalog setup for kirana and grocery shops',
      'Simple Web and WhatsApp ordering interface',
      'Store pickup or 30-minute hyperlocal delivery options',
      'Neighborhood promotion banners and daily offers',
    ],
  },
  {
    title: 'ResumePro',
    shortDescription: 'Modern ATS-optimized resume builder and expert review service for students and graduates.',
    problemStatement: 'Resume creation and review service.',
    targetAudience: 'Students, fresh graduates, job seekers',
    category: 'Career & Education',
    industry: 'Career & Education',
    revenueModel: 'One-time resume fees, premium templates, subscription',
    complexityLevel: 'beginner',
    keyFeatures: [
      'ATS-compliant resume builder with live score audit',
      'Domain expert human review and feedback turnaround',
      'One-click PDF download and LinkedIn profile export',
      'Role-specific bullet point recommendation engine',
    ],
  },
  {
    title: 'ReelMaker',
    shortDescription: 'On-demand short video and reel creation agency platform for local brands and startups.',
    problemStatement: 'Businesses request short promotional videos.',
    targetAudience: 'Small businesses, startups, local shops',
    category: 'Marketing & Media',
    industry: 'Marketing & Media',
    revenueModel: 'Video creation fees, monthly content packages',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'On-demand short video script and reel request portal',
      'Trending music and format alignment engine',
      'Rapid 48-hour video edit delivery turnaround',
      'Monthly content bundles for Instagram and YouTube Shorts',
    ],
  },
  {
    title: 'SocialStarter',
    shortDescription: 'Affordable, ready-to-deploy monthly social media management packages for local businesses.',
    problemStatement: 'Social-media content packages for small businesses.',
    targetAudience: 'Small businesses, local shops, startups',
    category: 'Digital Marketing',
    industry: 'Digital Marketing',
    revenueModel: 'Monthly social media management plans',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Monthly scheduled post, banner, and reel content calendar',
      'Local business brand identity and bilingual caption writing',
      'Multi-platform automated posting schedule',
      'Monthly audience growth and follower engagement analytics',
    ],
  },
  {
    title: 'LocalDelivery',
    shortDescription: 'On-demand hyperlocal logistics and courier network connecting shops with delivery runners.',
    problemStatement: 'Connect local shops with delivery partners.',
    targetAudience: 'Customers of local shops',
    category: 'Logistics & Delivery',
    industry: 'Logistics & Delivery',
    revenueModel: 'Delivery charges, business subscription plans',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Point-to-point intra-city parcel delivery dispatch',
      'Pooled on-demand delivery runner network',
      'Live GPS shipment tracking and SMS delivery updates',
      'Cash-on-delivery collection and immediate merchant credit',
    ],
  },
  {
    title: 'HomeHelp',
    shortDescription: 'Book trusted, professional home cleaning, appliance servicing, and deep sanitation.',
    problemStatement: 'Book cleaning and home-maintenance services.',
    targetAudience: 'Homeowners, tenants, households',
    category: 'Home Services',
    industry: 'Home Services',
    revenueModel: 'Commission per booking, service-provider subscription',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Comprehensive home deep cleaning and appliance repair packages',
      'Verified, background-screened, and rated service teams',
      'Transparent flat-rate pricing with no hidden charges',
      '100% satisfaction re-service guarantee policy',
    ],
  },
  {
    title: 'SurpriseBox',
    shortDescription: 'Bespoke curated celebration gift boxes customized for birthdays, anniversaries, and milestones.',
    problemStatement: 'Personalized birthday and anniversary gift packages.',
    targetAudience: 'People planning birthdays, anniversaries and special occasions',
    category: 'Gifts & E-Commerce',
    industry: 'Gifts & E-Commerce',
    revenueModel: 'Gift-box sales margin, customisation charges, subscriptions',
    complexityLevel: 'intermediate',
    keyFeatures: [
      'Interactive celebration gift box builder',
      'Themed birthday, anniversary, and congratulations packages',
      'Personalized polaroid photos and handwritten greeting letters',
      'Scheduled midnight or express surprise doorstep delivery',
    ],
  },
];