// Default startup idea pool for the BUILD2PITCH event (30 ideas).
// No copyrighted products, logos, or movie references.
module.exports = [
  {
    title: 'KrishiKonnect',
    shortDescription: 'Hyperlocal advisory + B2C marketplace connecting smallholder farmers directly to chefs and kirana shops.',
    problemStatement: 'Smallholder farmers lose 15-30% of margins to middlemen and often miss market prices. They need a single app to get weather-aligned farm advice and sell surplus produce at fair prices without intermediaries.',
    targetAudience: 'Smallholder farmers, local chefs, kirana/retail buyers',
    category: 'AgriTech',
    industry: 'AgriTech',
  },
  {
    title: 'MediQueue',
    shortDescription: 'Real-time outpatient queue and token management for public hospitals.',
    problemStatement: 'Patients in public hospitals wait hours standing in unmanaged queues with no visibility of wait times, leading to missed appointments and frustration for staff.',
    targetAudience: 'Public hospital outpatients, hospital administrators',
    category: 'HealthTech',
    industry: 'HealthTech',
  },
  {
    title: 'SwasthyaAid',
    shortDescription: 'AI triage assistant that helps community health workers screen symptoms in low-connectivity rural settings.',
    problemStatement: 'Community health workers handle dozens of cases daily with limited training and unreliable connectivity, making consistent triage and referral decisions hard.',
    targetAudience: 'ASHA/ANM community health workers, rural primary health centers',
    category: 'HealthTech',
    industry: 'HealthTech',
  },
  {
    title: 'CampusCash',
    shortDescription: 'Closed-loop payment wallet for campus canteens, events, and book shops.',
    problemStatement: 'Students juggle cash, UPI, and coupon books across the campus. Vendors face reconciliation pain and miss loyalty data on repeat buyers.',
    targetAudience: 'College students, campus vendors, fest organizers',
    category: 'FinTech',
    industry: 'FinTech',
  },
  {
    title: 'ReLeaf',
    shortDescription: 'Reverse vending machines that turn empty PET bottles into reward points and recycled pellets.',
    problemStatement: 'Plastic waste collection is disorganized; recyclers struggle to get clean sorted feedstock, while consumers discard bottles in streets and drains.',
    targetAudience: 'Corporates with cafeterias, residential complexes, municipal bodies',
    category: 'CleanTech',
    industry: 'CleanTech',
  },
  {
    title: 'InstaSpares',
    shortDescription: 'Verified marketplace for used and refurbished auto spare parts with warranty and fit-check.',
    problemStatement: 'Genuine used spare parts are impossible to find online; scrapyards and mechanics lack trust, fit-guarantee, and logistics, so vehicles get scrapped early.',
    targetAudience: 'Independent garages, fleet owners, scrapyard dealers',
    category: 'Mobility',
    industry: 'Mobility',
  },
  {
    title: 'TutorLink',
    shortDescription: 'Peer-to-peer tutoring marketplace matching nearby students with vetted college tutors.',
    problemStatement: 'Coaching centers are expensive and far away. Students need affordable, verified tutors nearby, but there is no trust layer to discover or book them.',
    targetAudience: 'School/college students, college tutors, parents',
    category: 'EdTech',
    industry: 'EdTech',
  },
  {
    title: 'FixmyRide',
    shortDescription: 'On-demand doorstep repair vans for two-wheelers with upfront pricing and live tracking.',
    problemStatement: 'Two-wheeler breakdowns waste hours at unorganized roadside mechanics with no pricing transparency or warranty on fixes.',
    targetAudience: 'Commuters and delivery riders with two-wheelers',
    category: 'Mobility',
    industry: 'Mobility',
  },
  {
    title: 'ColdChain Connect',
    shortDescription: 'Low-cost temperature monitoring and logistics matching for perishables like milk, fish, and fresh produce.',
    problemStatement: 'Cold chains are expensive to deploy; small dairy/fish suppliers lose stock to spoilage and cannot prove temperature compliance to buyers.',
    targetAudience: 'Dairy/fish/vegetable suppliers, cold storage operators',
    category: 'LogiTech',
    industry: 'LogiTech',
  },
  {
    title: 'SolarPay',
    shortDescription: 'Pay-per-day solar panel leasing for residential rooftops with remote monitoring.',
    problemStatement: 'High upfront cost blocks household adoption of rooftop solar. Owners also cannot track panel health after installation.',
    targetAudience: 'Urban homeowners, housing societies, small businesses',
    category: 'Energy',
    industry: 'Energy',
  },
  {
    title: 'SkillKart',
    shortDescription: 'Micro-skills marketplace where learners complete short industry badges and get matched to gig-hiring companies.',
    problemStatement: 'Fresh graduates have degrees but lack the specific micro-skills employers want, and companies waste weeks filtering applicants.',
    targetAudience: 'Students, freshers, gig-employers',
    category: 'EdTech',
    industry: 'EdTech',
  },
  {
    title: 'Paper2Pixel',
    shortDescription: 'Fast digitization and searchable indexing of legacy paper records for municipal and small government offices.',
    problemStatement: 'Civic record-keeping is still paper-first: searching for one file takes hours, decisions stall, and documents decay.',
    targetAudience: 'Municipal offices, panchayats, cooperative societies',
    category: 'GovTech',
    industry: 'GovTech',
  },
  {
    title: 'FoodRescue',
    shortDescription: 'Connects surplus restaurant and event meals to shelters and staff canteens within the city.',
    problemStatement: 'Tonnes of safe-to-eat food is wasted daily while shelters feed people unsustainably; logistics and trust are missing between donor and receiver.',
    targetAudience: 'Restaurants, event organizers, shelters, NGO kitchens',
    category: 'SocialImpact',
    industry: 'SocialImpact',
  },
  {
    title: 'Drishti AI',
    shortDescription: 'OCR + ML document pipeline that turns invoices, vouchers, and bills into clean ledgers for small accountants.',
    problemStatement: 'Accountants manually re-type hundreds of invoices a month, causing errors and overtime; small firms cannot afford enterprise RPA tools.',
    targetAudience: 'Small CA firms, freelance accountants, MSME finance teams',
    category: 'AI/Data',
    industry: 'AI/Data',
  },
  {
    title: 'RiteRx',
    shortDescription: 'Prescription-verified medicine reminders with affordable generic delivery at home.',
    problemStatement: 'Patients stop taking medicines because refills are inconvenient and generics are hard to locate, worsening chronic disease outcomes.',
    targetAudience: 'Chronic-care patients, caregivers, senior citizens',
    category: 'HealthTech',
    industry: 'HealthTech',
  },
  {
    title: 'TrashTrack',
    shortDescription: 'IoT fill-level sensors on dumpsters with route optimization for collection crews.',
    problemStatement: 'Waste collection follows fixed schedules, so bins overflow or are emptied half-empty; municipalities burn fuel and residents complain.',
    targetAudience: 'Municipal corporations, gated communities, facility managers',
    category: 'SmartCity',
    industry: 'SmartCity',
  },
  {
    title: 'NayaSawari',
    shortDescription: 'Battery-swapping kiosk network for electric rickshaws and delivery bikes.',
    problemStatement: 'EV adoption stalls because charging takes hours and squeezes driver earnings; batteries degrade fast with deep discharges.',
    targetAudience: 'E-rickshaw/e-bike drivers, delivery fleets',
    category: 'EV/Mobility',
    industry: 'EV/Mobility',
  },
  {
    title: 'Croptech IoT',
    shortDescription: 'Soil sensors with automated micro-irrigation control for small farms.',
    problemStatement: 'Farmers over-water or under-water crops by instinct, wasting power and water; sensors exist but are priced for large agribusiness.',
    targetAudience: 'Small/medium farmers, FPOs, agricultural extension officers',
    category: 'AgriTech',
    industry: 'AgriTech',
  },
  {
    title: 'BuildBazzaar',
    shortDescription: 'B2B marketplace for construction materials with logistics, credit, and price transparency.',
    problemStatement: 'Small builders buy materials from several unreliable dealers with opaque pricing, delayed deliveries, and no credit history to leverage.',
    targetAudience: 'Small contractors, material dealers, construction crews',
    category: 'LogiTech',
    industry: 'LogiTech',
  },
  {
    title: 'ExamSharp',
    shortDescription: 'AI-generated practice tests mapped section-by-section to board and entrance syllabi.',
    problemStatement: 'Students practice from a handful of generic test books that never mirror the actual syllabus weightage, so preparation is hit-or-miss.',
    targetAudience: 'Board-exam students, entrance aspirants, teachers',
    category: 'EdTech',
    industry: 'EdTech',
  },
  {
    title: 'WalletWatch',
    shortDescription: 'Expense-aware savings companion that rounds up spends and invests micro-amounts for first-time earners.',
    problemStatement: 'First-time earners save little because they have no idea where money goes, and investing feels heavy and academic.',
    targetAudience: 'Interns, freshers, early-career professionals',
    category: 'FinTech',
    industry: 'FinTech',
  },
  {
    title: 'VetPal',
    shortDescription: 'Tele-consultations and doorstep vaccination drives for pets in tier-2 cities.',
    problemStatement: 'Pet care is concentrated in metro cities; owners elsewhere struggle to reach a vet, delay treatments, and skip vaccinations.',
    targetAudience: 'Pet owners in tier-2/3 cities, local veterinary clinics',
    category: 'HealthTech',
    industry: 'HealthTech',
  },
  {
    title: 'CraftLoop',
    shortDescription: 'Export-managed marketplace for handicraft artisans covering packaging, QC, and customs.',
    problemStatement: 'Artisans create world-class craft but cannot export: they lack packaging standards, quality certification, and cross-border logistics.',
    targetAudience: 'Handicraft artisans, craft clusters, export aggregators',
    category: 'Ecommerce',
    industry: 'Ecommerce',
  },
  {
    title: 'BackpackBudget',
    shortDescription: 'Budget trip planner that groups solo travelers into verified local tour pods.',
    problemStatement: 'Solo and small-group travelers get overcharged by ad-hoc tour operators and miss trustable local experiences within their budget.',
    targetAudience: 'Young travelers, budget hostel-goers, local tour guides',
    category: 'TravelTech',
    industry: 'TravelTech',
  },
  {
    title: 'WifiWale',
    shortDescription: 'Community-managed Wi-Fi hotspots for hostels, PG clusters, and residential societies.',
    problemStatement: 'Internet plans are sold per-home, yet hostels and PGs need shared, fair-usage Wi-Fi with per-user billing and simple admin.',
    targetAudience: 'Hostel/PG owners, housing societies, internet resellers',
    category: 'Connectivity',
    industry: 'Connectivity',
  },
  {
    title: 'GreenGrub',
    shortDescription: 'Food-delivery packaging with reusable containers and a refundable-deposit loop.',
    problemStatement: 'Single-use packaging forms a huge share of urban waste; consumers like sustainability but will not switch if it is inconvenient or costs more.',
    targetAudience: 'Food-delivery platforms, cloud kitchens, office employees',
    category: 'FoodTech',
    industry: 'FoodTech',
  },
  {
    title: 'RefurbHub',
    shortDescription: 'Certified refurbished smartphones and laptops with transparent grading, warranty, and buyback.',
    problemStatement: 'E-waste grows while affordable devices are scarce; consumers fear fake or poorly graded refurbs, so trust is the main blocker.',
    targetAudience: 'Budget shoppers, students, enterprise IT refresh programs',
    category: 'ConsumerTech',
    industry: 'ConsumerTech',
  },
  {
    title: 'SafeStreet',
    shortDescription: 'Emergency SOS wearable paired with a trained community-response network.',
    problemStatement: 'Emergency response depends on slow helplines and distance; a panic button alone does not dispatch local help fast enough.',
    targetAudience: 'Working professionals, students in hostels, night-shift workers',
    category: 'SafetyTech',
    industry: 'SafetyTech',
  },
  {
    title: 'NutriRise',
    shortDescription: 'Affordable fortified snacks designed for mid-day meal programs and anganwadi centers.',
    problemStatement: 'Government nutrition programs fight hidden anaemia and malnutrition but rely on bland, unappealing, and under-fortified rations.',
    targetAudience: 'Mid-day meal workers, anganwadis, NGOs, schools',
    category: 'FoodTech',
    industry: 'FoodTech',
  },
  {
    title: 'IDBridge',
    shortDescription: 'Interoperable video-KYC and digital-identity verification for small merchants onboarding into formal finance.',
    problemStatement: 'Small merchants struggle to onboard into banking, insurance, and lending because manual KYC checks are slow, repetitive, and costly.',
    targetAudience: 'Small merchants, NBFCs, banks, insurers, KYC agents',
    category: 'FinTech',
    industry: 'FinTech',
  },
];